/*1. SELECT * FROM EMPLEADOS*/
/*2. SELECT * FROM DEPARTAMENTOS*/
/*3. SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS*/
/*4. SELECT NOMBRE, SAL_EMP FROM EMPLEADOS*/
/*5. SELECT COMISION_EMP FROM EMPLEADOS*/
/*6. SELECT * FROM EMPLEADOS WHERE CARGO_EMP='SECRETARIA'*/
/*7. SELECT * FROM EMPLEADOS WHERE CARGO_EMP='VENDEDOR' ORDER BY NOMBRE */
/*8. SELECT NOMBRE,CARGO_EMP FROM EMPLEADOS ORDER BY SAL_EMP */
/*9. SELECT NOMBRE_JEFE_DEPTO FROM DEPARTAMENTOS WHERE CIUDAD='CIUDAD REAL'*/
/*10. SELECT NOMBRE AS Nombre, CARGO_EMP AS Cargo FROM EMPLEADOS*/
/*11. SELECT SAL_EMP, COMISION_EMP FROM EMPLEADOS WHERE ID_DEPTO=2000 ORDER BY COMISION_EMP ASC*/
/*12. SELECT NOMBRE, (SAL_EMP+COMISION_EMP+500) FROM EMPLEADOS WHERE ID_DEPTO=3000 order by NOMBRE*/
/*13. SELECT NOMBRE FROM EMPLEADOS WHERE NOMBRE LIKE 'J%'*/
/*14. SELECT SAL_EMP, COMISION_EMP, SAL_EMP+COMISION_EMP FROM EMPLEADOS WHERE COMISION_EMP>1000*/
/*15. SELECT SAL_EMP, COMISION_EMP FROM EMPLEADOS WHERE COMISION_EMP=0*/
/*16. SELECT * FROM EMPLEADOS WHERE COMISION_EMP>SAL_EMP*/
/*17. SELECT * FROM EMPLEADOS WHERE COMISION_EMP<=(SAL_EMP*0.3)*/
/*18. SELECT * FROM EMPLEADOS WHERE NOMBRE NOT LIKE '%MA%'*/
/*19. SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS WHERE NOMBRE_DEPTO IN ('VENTAS','INVESTIGACION','MANTENIMIENTO')*/
/*19. SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS WHERE NOMBRE_DEPTO LIKE 'VENTAS' OR NOMBRE_DEPTO LIKE 'INVESTIGACION' OR NOMBRE_DEPTO LIKE 'MANTENIMIENTO'*/
/*20. SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS WHERE NOMBRE_DEPTO NOT IN ('VENTAS','INVESTIGACION','MANTENIMIENTO')*/
/*20. SELECT NOMBRE_DEPTO FROM DEPARTAMENTOS WHERE (NOMBRE_DEPTO NOT LIKE 'VENTAS') AND (NOMBRE_DEPTO NOT LIKE 'INVESTIGACION') AND (NOMBRE_DEPTO NOT LIKE 'MANTENIMIENTO')*/
/*21. SELECT MAX(SAL_EMP) FROM EMPLEADOS */
/*22. SELECT NOMBRE FROM EMPLEADOS ORDER BY NOMBRE DESC LIMIT 1*/
/*23. SELECT MAX(SAL_EMP), MIN(SAL_EMP), MAX(SAL_EMP)-MIN(SAL_EMP) FROM EMPLEADOS*/
/*24. SELECT ID_DEPTO,AVG(SAL_EMP) FROM EMPLEADOS group by ID_DEPTO*/
/*25. SELECT ID_DEPTO,count(ID_EMP) FROM EMPLEADOS GROUP BY ID_DEPTO HAVING count(ID_EMP)>3*/
/*26. SELECT ID_DEPTO FROM EMPLEADOS GROUP BY ID_DEPTO HAVING count(ID_EMP)=0
	  select * from departamentos where id_depto not in(select distinct id_depto from empleados)*/
/*27. SELECT * FROM EMPLEADOS JOIN DEPARTAMENTOS ON EMPLEADOS.ID_DEPTO = DEPARTAMENTOS.ID_DEPTO*/
/*28. SELECT * FROM EMPLEADOS WHERE SAL_EMP<(SELECT avg(SAL_EMP) FROM EMPLEADOS)*/